name: My first project
on: workflow_dispatch
jobs:
   firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello"
      
      - name: checkout branch 
        uses: actions/checkout@v3

      
