name: firstproject
on: workflow_dispatch
env:
   mypass: ${{ env.TESTTT }}
jobs:
   first:
     runs-on: ubuntu-latest
     steps:
          - name: This is my first code
            run: echo "${{env.mypass}}" >> y1.yaml

          - name: This is my first code
            run: cat y1.yaml

 
