name: firstproject
on: workflow_dispatch
env:
   mypass: ${{ secret.MYPASS}}
jobs:
   first:
     runs-on: ubuntu-latest
     steps:
          - name: This is my first code
            run: echo "${{env.mypass}}"

 
