name: firstproject
on: workflow_dispatch
jobs:
   first:
     runs-on: ubuntu-latest
     steps:
          - name: This is my first code
            run: echo "Hello"
          - name: checkout branch
            uses: actions/checkout@v3
          - name: get PWD
            run: pwd
          - name: get ls
            run: ls
     
